### ISSUE TITLE
bad-import-yang-version is raised for legal YANG 1.0 imports

### ISSUE THREAD

**Issue by esmasth** [TypeFox/yang-lsp#228]
https://www.rfc-editor.org/rfc/rfc7950#section-12 specifies that YANG1.0 module importing YANG1.1 module is allowed when importing without revision. Is that yang-lsp development community's interpretation as well?

For example, iana-if-type.yang (YANG 1.0) importing ietf-interfaces.yang (YANG1.1) is raised as an error, and I would not like to suppress it globally.

**Comment by esmasth** [comment]
@dhuebner, should we consider it as a bugfix, since it raises a false positive error and not a warning?

**Comment by dhuebner** [comment]
@esmasth 
Can we close this now? Or is there something left?

**Comment by esmasth** [comment]
Ok to close. I don't have more in the pipeline in this context.
